FROM docker:dind

WORKDIR /app 

RUN apk get update && \
    apk add --no-cache bash python3 py3-pip

RUN pip install aws-sam-cli --break-system-packages
ADD release/linux/arm64/plugin /bin/


ENTRYPOINT ["/bin/plugin"]