FROM alpine:latest

RUN apk get update && \
    apk add --no-cache python3 py3-pip ca-certificates

RUN pip install aws-sam-cli --break-system-packages
RUN pip install awscli --break-system-packages

ADD release/linux/arm64/plugin /bin/

ENTRYPOINT ["/bin/plugin"]
